# Generated by Django 4.0.5 on 2022-06-22 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_tag_article_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
    ]
