# Generated by Django 4.0.5 on 2022-06-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_video_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='article',
            name='videos',
            field=models.ManyToManyField(blank=True, to='blog.video'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
